adds template + CSS for contact compontent
localgovdrupal/localgov_base pull request #695
Opened 2024-12-19 12:30 UTC by markconroy

Closes #421

## Note
This is not ready for testing just yet.
- [  ] Wait to get designs from Designer Dave and see about implementing them
- [  ] Update the CSS to use custom variables instead of generic ones.

## What does this change?

Adds a template + CSS for contact component.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2025-01-28 12:42 UTC, markconroy commented
This got the 👍 from Clear Spot Media, https://github.com/localgovdrupal/localgov_base/issues/421#issuecomment-2609565147

2025-02-04 13:43 UTC, millnut commented
@ekes I've re-run the tests only failures are eslint and stylelint which I think have already been fixed on 2.x

2025-02-17 18:05 UTC, msayoung commented
@markconroy - great!

A couple of things:

- the label for the Other team.localgov_contact.URL probably needs fixing
- Repetition of the Office Hours heading and label
- The Contact component title is showing above the component. 
- There's a bit more padding above the Phone heading, so its misaligned with Email and Website

2025-02-18 12:39 UTC, finnlewis submitted a review, later dismissed
@markconroy looks like @msayoung has requested some changes, so we'll leave this with you for now.

2025-02-20 09:03 UTC, markconroy commented
To do

- [ ] the label for the Other team.localgov_contact.URL probably needs fixing
- [ ] Repetition of the Office Hours heading and label
- [ ] The Contact component title is showing above the component.
- [ ] There's a bit more padding above the Phone heading, so its misaligned with Email and Website

2025-02-25 10:24 UTC, markconroy commented
@msayoung I've completed checkbox 4 above, but the first three are config items not localgov_base items.

> the label for the Other team.localgov_contact.URL probably needs fixing
> Repetition of the Office Hours heading and label
> The Contact component title is showing above the component.

So ... I think this is ready to be approved and councils can remove those field labels showing in their own config and/or we can remove them by default in our other corresponding repos.

2025-02-25 12:09 UTC, msayoung commented
@markconroy - sorry I'm still seeing extra padding above the Phone item. We've also lost space between the titles and fields.

2025-04-07 08:57 UTC, markconroy commented
@msayoung this is ready again.

2025-04-10 12:43 UTC, msayoung approved these changes

2025-04-10 12:44 UTC, msayoung approved these changes
styles fine now, thanks.

2025-04-10 12:54 UTC, msayoung commented
One thing I noticed is that we're getting a heading for Email whether or not there is anything in that field.

2025-04-10 12:57 UTC, msayoung requested changes

2025-04-10 12:57 UTC, msayoung commented on templates/paragraphs/paragraph--localgov-contact.html.twig
> +		{% if has_email_website_fields %}{% endif %}
I think this is supposed to wrap the block above.

2025-04-11 10:18 UTC, markconroy commented on templates/paragraphs/paragraph--localgov-contact.html.twig
> +		{% if has_email_website_fields %}{% endif %}
Fixed, can't believe I made such a rookie mistake!

2025-04-11 10:19 UTC, markconroy commented
@msayoung ready again!

2025-04-14 07:50 UTC, msayoung commented on templates/paragraphs/paragraph--localgov-contact.html.twig
> +		{% if has_email_website_fields %}{% endif %}
I assume you left it to check my QA skills ;)

2025-04-14 07:51 UTC, msayoung approved these changes

2025-04-15 15:05 UTC, merged